[package]
name = "cagra-parser"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies.cagra]
path = ".."

[dependencies.syn]
version = "*"
features = ["full"]

[dependencies]
quote = "*"
proc-macro2 = "*"
