language: rust
sudo: false
dist: trusty

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo build -vv
  - cargo test -vv

env:
  - RUST_BACKTRACE=1
