language: rust
sudo: false
dist: trusty

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo test -vv

addons:
  apt:
    packages:
      - cmake
      - gfortran

env:
  - RUST_BACKTRACE=1
