[package]
name = "cagra-hamilton"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
edition = "2018"

[dependencies.cagra]
path = "../cagra"

[dependencies]
failure = "0.1"
